Fix url and path when version regex specified
mjcheetham/update-winget pull request #124
Opened 2021-06-16 19:57 UTC by ldennington

Making a couple tweaks to finish up the changes to handle special microsoft/git versioning. Specifically, we need to ensure the path version aligns with the manifest version (winget requirement) and pass the `fullUrl` rather than `url` for formatting.

2021-06-17 22:01 UTC, ldennington commented on dist/index.js
> +    var _a, _b, _c, _d;
This is an auto-generated file from `npm run all`. @mjcheetham can correct me if I'm wrong, but I don't think we normally look at the diff.

2021-06-18 09:29 UTC, mjcheetham commented on dist/index.js
> +    var _a, _b, _c, _d;
Correct. This Action is written in TypeScript, so the JavaScript files are all generated output.
Don't bother looking at any .js files.

2021-06-18 09:35 UTC, mjcheetham requested changes
@ldennington We're assuming here that the first instance of a `{{version:R}}` regex pattern R in the manifest text template is the one that should be used for the manifest file path?

I think it would be better to have the manifest be generated, and then re-inspect the end result looking for the `PackageVersion` property and use that value as the version file path.
This would ensure that the manifest is definitely valid in the eyes of the `winget-pkgs` repo (the `PackageVersion` and file path version must match).

Left some suggestions/diffs that would do that (generate the manifest and lookup the final `PackageVersion` value). Let me know what you think!

2021-06-18 09:35 UTC, mjcheetham commented on src/main.ts
> +
```suggestion
```

2021-06-18 09:35 UTC, mjcheetham commented on src/main.ts
> +    )}/${id}.yaml`.trim();
```suggestion
      .toLowerCase()}/${id.replace('.', '/')}/${pathVersion}/${id}.yaml`.trim();
```

2021-06-18 09:35 UTC, mjcheetham commented on src/main.ts
```suggestion

core.debug(
  "computing file path version from final manifest property 'PackageVersion'..."
);
const pkgVerRegEx = /PackageVersion:\s*(?<version>.*)/;
const pkgVerMatch = manifestText.match(pkgVerRegEx);
let pathVersion: string | undefined;
if (pkgVerMatch?.groups?.version) {
  pathVersion = pkgVerMatch.groups.version;
} else {
  core.warning(
    "could not match 'PackageVersion' property in manifest; manifest may not be valid!"
  );
  pathVersion = version.toString();
}
core.debug(`path version is ${pathVersion}`);

```

2021-06-18 17:14 UTC, ldennington commented
> @ldennington We're assuming here that the first instance of a `{{version:R}}` regex pattern R in the manifest text template is the one that should be used for the manifest file path?
> 
> I think it would be better to have the manifest be generated, and then re-inspect the end result looking for the `PackageVersion` property and use that value as the version file path.
> This would ensure that the manifest is definitely valid in the eyes of the `winget-pkgs` repo (the `PackageVersion` and file path version must match).
> 
> Left some suggestions/diffs that would do that (generate the manifest and lookup the final `PackageVersion` value). Let me know what you think!
> 
> (Created a branch based off of this one with the suggestion commits below here: https://github.com/mjcheetham/update-winget/tree/path-version)

Mmm I don't think those updates quite worked - when I tested, `vfs` is still included in all the versions (see https://github.com/ldennington/winget-playground/pull/42/files). I'll try to dig in and fix today.

2021-06-18 17:30 UTC, ldennington commented
> > @ldennington We're assuming here that the first instance of a `{{version:R}}` regex pattern R in the manifest text template is the one that should be used for the manifest file path?
> > I think it would be better to have the manifest be generated, and then re-inspect the end result looking for the `PackageVersion` property and use that value as the version file path.
> > This would ensure that the manifest is definitely valid in the eyes of the `winget-pkgs` repo (the `PackageVersion` and file path version must match).
> > Left some suggestions/diffs that would do that (generate the manifest and lookup the final `PackageVersion` value). Let me know what you think!
> > (Created a branch based off of this one with the suggestion commits below here: https://github.com/mjcheetham/update-winget/tree/path-version)
> 
> Mmm I don't think those updates quite worked - when I tested, `vfs` is still included in all the versions (see https://github.com/ldennington/winget-playground/pull/42/files). I'll try to dig in and fix today.

Never mind. It helps when I use the correct yml for testing. Please ignore the above comment.

2021-06-18 17:37 UTC, mjcheetham approved these changes

2021-06-18 17:38 UTC, merged